using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    private Spaceship _spaceship;

    // Start is called before the first frame update
    void Start()
    {
        혎mmand현nter 絪mmand현nter = new 혎mmand현nter(4, "lala", 100, 100);
        絪mmand현nter.AddBody(new Body(4, "lala", 100, 100), 0);
        絪mmand현nter.AddModule(new Battery("lala", 100, 100, 1000, 0), 0, 0);
        絪mmand현nter.AddModule(new Battery("lala", 100, 100, 1000, 0), 0, 1);
        絪mmand현nter.AddModule(new Battery("lala", 100, 100, 1000, 0), 0, 2);
        絪mmand현nter.AddModule(new Battery("lala", 100, 100, 1000, 0), 0, 3);
        _spaceship = new Spaceship(0, 絪mmand현nter);
        Debug.Log(_spaceship.GetStrength());
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
